### ISSUE TITLE
Av::CommandError - error while running command

### ISSUE THREAD

**Issue by Murphysc** [ruby-av/paperclip-av-transcoder#7] opened 2015-01-21 19:43 UTC
I wasn't really sure where else to try and get help with my issues so I ended up posting here. Whenever I add styles to the file upload I get this error:

    Command :: PATH=/usr/local/bin/:$PATH file -b --mime '/var/folders/9y/6w60_d8n3p5084sxpnl6kj900000gn/T/fe208ed3e8facea9700ed13929aef73720150121-32345-8vcuoz.mov'
    [AV] Running command: if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi
    sh: -c: line 0: syntax error near unexpected token `then'
    sh: -c: line 0: `PATH=/usr/local/bin/:$PATH if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi'
    Completed 500 Internal Server Error in 861ms

    Av::CommandError (error while running command if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi: Command 'PATH=/usr/local/bin/:$PATH if command -v avprobe 2>/dev/null; then echo "true"; else echo "false"; fi' returned 2. Expected 0
    Here is the command output:

    ):

I don't really have any experience when interacting with gems and I haven't been able to find anything on this issue. Any help is greatly appreciated.

Thanks

**Comment by Murphysc** [comment] 2015-01-21 20:01
Looking at `paperclip-ffmpeg` I saw a similar [issue](https://github.com/owahab/paperclip-ffmpeg/issues/46) . I have implemented `paperclip-ffmpeg` and set the version to `1.0.1`. Not sure if this is going to be a good solution for long term use.

**Comment by owahab** [comment] 2015-03-02 10:03
Possible duplicate of #8

**Closed by owahab** 2015-03-02 10:03 UTC
